### ISSUE TITLE
Work in Progress?

### ISSUE THREAD

**Issue by ashes999** [cremno/mruby-allegro#2]
Hi,

The readme for this project says it's still a "work in progress" and the last commit was in 2014 (about a year ago). Is it still under development? Is it in a usable, workable state? I see a good list of examples in the repository.

**Comment by cremno** [comment]
> Is it still under development? 

No, but if something small-ish is missing, I might add it myself. Just create a new issue - or even a PR.

> Is it in a usable, workable state?

Well, it's far from a complete binding. I think most of the more advanced stuff is missing. Otherwise it should be usable.
